
{
    'name': 'Hospital Management',
    'version': '1.0.0',
    'category': 'Hospital',
    'author': 'Fager Mohsen',
    'sequence': -100,
    'summary': 'Hospital Management Sysytem',
    'description': """ Hospital Management Sysytem """,
    'depends': ['mail', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'data/patient_tag_data.xml',
        'data/patient.tag.csv',
        'wizard/cancel_appointment_views.xml',
        'views/menu.xml',
        'views/patient_views.xml',
        'views/female_patient_views.xml',
        'views/male_patient_views.xml',
        'views/appointment_views.xml',
        'views/patient_tag_views.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
    'assets': {},
}
